# Device Path
DEVICE_PATH := device/realme/RMX3782

# Platform & Architecture
TARGET_BOARD_PLATFORM := mt6835
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_VARIANT := cortex-a55
TARGET_SUPPORTS_64_BIT_APPS := true

# A/B Partitions
AB_OTA_UPDATER := true
BOARD_USES_RECOVERY_AS_BOOT := true
TW_HAS_NO_RECOVERY_PARTITION := true

# Boot image config
BOARD_BOOTIMAGE_PARTITION_SIZE := 67108864
BOARD_VENDOR_BOOTIMAGE_PARTITION_SIZE := 100663296
BOARD_INCLUDE_DTB_IN_BOOTIMG := true
BOARD_BOOTIMG_HEADER_VERSION := 4

# Kernel (prebuilt from OTA)
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/Image.gz
BOARD_PREBUILT_DTB := $(DEVICE_PATH)/prebuilt/dtb.img
BOARD_MKBOOTIMG_ARGS += --header_version 4
BOARD_MKBOOTIMG_ARGS += --dtb $(BOARD_PREBUILT_DTB)

# Kernel options
BOARD_KERNEL_IMAGE_NAME := Image.gz
TARGET_KERNEL_CONFIG := RMX3782_defconfig
TARGET_KERNEL_SOURCE := kernel/realme/RMX3782
TARGET_FORCE_PREBUILT_KERNEL := true

# Ramdisk (prebuilt vendor ramdisk from OTA)
BOARD_INCLUDE_RECOVERY_RAMDISK := true
BOARD_VENDOR_RAMDISK_RECOVERY := true
BOARD_RAMDISK_USE_LZ4 := true
BOARD_PREBUILT_VENDOR_RAMDISK := $(DEVICE_PATH)/ramdisk
BOARD_PREBUILT_RECOVERY_RC := $(DEVICE_PATH)/ramdisk/init.recovery.project.rc

# Filesystems
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := f2fs
BOARD_FLASH_BLOCK_SIZE := 262144

# Dynamic Partitions
BOARD_SUPER_PARTITION_SIZE := 9126805504
BOARD_SUPER_PARTITION_GROUPS := realme_dynamic_partitions
BOARD_REALME_DYNAMIC_PARTITIONS_PARTITION_LIST := system vendor product odm my_product my_region my_carrier my_heytap my_stock my_engineering my_bigball my_preload my_company my_manifest
BOARD_REALME_DYNAMIC_PARTITIONS_SIZE := 9122611200

# Recovery
TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery.fstab

# Verified Boot & Anti-Rollback
BOARD_AVB_ENABLE := true
BOARD_AVB_MAKE_VBMETA_IMAGE_ARGS += --flags 3
PLATFORM_SECURITY_PATCH := 2099-12-31
VENDOR_SECURITY_PATCH := 2099-12-31
PLATFORM_VERSION := 16.1.0

# TWRP Flags
TW_THEME := portrait_hdpi
TW_DEFAULT_LANGUAGE := en
TW_USE_TOOLBOX := true
TW_INCLUDE_CRYPTO := true
TW_INCLUDE_REPACKTOOLS := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_SCREEN_BLANK_ON_BOOT := true
TW_INCLUDE_LPDUMP := true
TW_INCLUDE_FASTBOOTD := true
TW_INPUT_BLACKLIST := "hbtp_vm"

# Vendor output
TARGET_COPY_OUT_VENDOR := vendor

